### ISSUE TITLE
405 Method Not Allowed: When trying to run/save lua script

### ISSUE THREAD

**Issue by laurentchicoine** [gpsnmeajp/FlashTools-Lua-Editor#1]
When trying to run a lua script I get an error 405 Method Not Allowed.

I translated your website and I saw that ou mentionned the issue. I did try to use the unlock function but it did not work. I also tried disconnecting and reconnecting the card.

I have a W-04 flashair.

I did not see any documentation of support for a direct PUT method, maybe it would be more robust to use the upload.cgi. If you are open to that I might submit a pull request for this to update the worker.js to rather use upload.cgi commands.

**Comment by gpsnmeajp** [comment]
WebDAV(FlashAir Drive) function suppots PUT when WEBDAV=2. 
Did you try Autosetup in FTLE menu?

unlock button works to FAT unlock to host. Don't affect to FTLE.

**Comment by laurentchicoine** [comment]
I had WEBDAV=1. I did not use the autosetup since I had a configuration I wanted to keep. Setting WEBDAV=2 worked successfuly. If I encounter any other issues I will try to run Autosetup first.

Thanks a lot for the quick support.
